# local deploy only
version: '3'
services:
  postgres:
    image: postgres:15.5
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: apikeyman
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  migrate:
    image: 'jaspeen/apikeyman:${VERSION}'
    command: ["migrate", "--db", "postgresql://postgres:postgres@postgres:5432/apikeyman?sslmode=disable"]
    depends_on:
      - postgres
  apikeyman:
    image: 'jaspeen/apikeyman:${VERSION}'
    command: ['--log', 'DEBUG', "server", "--addr", "0.0.0.0:8080", "--db", "postgresql://postgres:postgres@postgres:5432/apikeyman?sslmode=disable"]
    depends_on:
      - migrate
    ports:
      - '8080:8080'
