{{- $podAnnotations := ternary .Values.deployment.podAnnotations .Values.podAnnotations (not (empty .Values.deployment.podAnnotations )) -}}
{{- $automountServiceAccountToken := ternary .Values.deployment.automountServiceAccountToken .Values.automountServiceAccountToken (not (empty .Values.deployment.automountServiceAccountToken )) -}}
{{- $livenessProbe := ternary .Values.deployment.livenessProbe .Values.livenessProbe (not (empty .Values.deployment.livenessProbe )) -}}
{{- $readinessProbe := ternary .Values.deployment.readinessProbe .Values.readinessProbe (not (empty .Values.deployment.readinessProbe )) -}}
{{- $autoscaling := ternary .Values.deployment.autoscaling .Values.autoscaling (not (empty .Values.deployment.autoscaling )) -}}
{{- $resources := ternary .Values.deployment.resources .Values.resources (not (empty .Values.deployment.resources )) -}}
{{- $extraInitContainers := ternary .Values.deployment.extraInitContainers .Values.extraInitContainers (not (empty .Values.deployment.extraInitContainers )) -}}
{{- $extraContainers := ternary .Values.deployment.extraContainers .Values.extraContainers (not (empty .Values.deployment.extraContainers )) -}}
{{- $extraLabels := ternary .Values.deployment.extraLabels .Values.extraLabels (not (empty .Values.deployment.extraLabels )) -}}
{{- $extraVolumeMounts := ternary .Values.deployment.extraVolumeMounts .Values.extraVolumeMounts (not (empty .Values.deployment.extraVolumeMounts )) -}}
{{- $extraVolumes := ternary .Values.deployment.extraVolumes .Values.extraVolumes (not (empty .Values.deployment.extraVolumes )) -}}
{{- $nodeSelector := ternary .Values.deployment.nodeSelector .Values.nodeSelector (not (empty .Values.deployment.nodeSelector )) -}}
{{- $affinity := ternary .Values.deployment.affinity .Values.affinity (not (empty .Values.deployment.affinity )) -}}
{{- $tolerations := ternary .Values.deployment.tolerations .Values.tolerations (not (empty .Values.deployment.tolerations )) -}}
{{- $topologySpreadConstraints := ternary .Values.deployment.topologySpreadConstraints .Values.topologySpreadConstraints (not (empty .Values.deployment.topologySpreadConstraints )) -}}
{{- include "apikeyman.automigration.typeVerification" . -}}
{{- $migrationExtraEnv := ternary .Values.deployment.automigration.extraEnv .Values.deployment.extraEnv (not (empty .Values.deployment.automigration.extraEnv )) -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apikeyman.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "apikeyman.labels" . | nindent 4 }}
    {{- with $extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.deployment.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
{{- if not $autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "apikeyman.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "apikeyman.annotations.checksum" . | indent 8 -}}
        {{- with $podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $.Values.deployment.podMetadata.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "apikeyman.selectorLabels" . | nindent 8 }}
        {{- with $extraLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $.Values.deployment.podMetadata.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
      {{- if $extraInitContainers}}
        {{- tpl $extraInitContainers . | nindent 8 }}
      {{- end }}
      {{- if and ( .Values.apikeyman.automigration.enabled ) ( eq .Values.apikeyman.automigration.type "initContainer" ) }}
        - name: {{ .Chart.Name }}-automigrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.apikeyman.automigration.customCommand }}
          command: {{- toYaml .Values.apikeyman.automigration.customCommand | nindent 12 }}
          {{- else }}
          command: ["apikeyman"]
          {{- end }}
          {{- if .Values.apikeyman.automigration.customArgs }}
          args: {{- toYaml .Values.apikeyman.automigration.customArgs | nindent 12 }}
          {{- else }}
          args: [ "migrate" ]
          {{- end }}
          volumeMounts:
            - name: {{ include "apikeyman.name" . }}-config-volume
              mountPath: /etc/config
              readOnly: true
          {{- with $extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- if not (empty ( include "apikeyman.dsn" . )) }}
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "apikeyman.secretname" . }}
                  key: dsn
            {{- end }}
            {{- with $migrationExtraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.apikeyman.automigration.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      serviceAccountName: {{ include "apikeyman.serviceAccountName" . }}
      automountServiceAccountToken: {{ $automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{- toYaml .Values.apikeyman.command | nindent 12 }}
          {{- if .Values.apikeyman.customArgs }}
          args: {{- toYaml .Values.apikeyman.customArgs | nindent 12 }}
          {{- else }}
          args:
            - --log
            - {{ .Values.apikeyman.config.logLevel }}
            - server
            - --cache-max-size
            - {{ .Values.apikeyman.config.cacheMaxSize }}
            - --cache-ttl
            - {{ .Values.apikeyman.config.cacheTTL | quote }}
            - --base-path
            - {{ .Values.apikeyman.config.basePath | quote }}
            - --addr
            - "0.0.0.0:{{ .Values.apikeyman.config.port }}"
          {{- end }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.apikeyman.config.port }}
              protocol: TCP
            {{- with .Values.deployment.extraPorts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          lifecycle:
            {{- toYaml .Values.deployment.lifecycle | nindent 12 }}
          livenessProbe:
            {{- if .Values.deployment.customLivenessProbe }} 
              {{- toYaml .Values.deployment.customLivenessProbe | nindent 12 }}
            {{- else }}
            httpGet:
              path: /health/alive
              port: {{ .Values.apikeyman.config.port }}
              httpHeaders:
                - name: Host
                  value: '127.0.0.1'
            {{- toYaml $livenessProbe | nindent 12 }}
            {{- end }}
          readinessProbe:
            {{- if .Values.deployment.customReadinessProbe }} 
              {{- toYaml .Values.deployment.customReadinessProbe | nindent 12 }}
            {{- else }}
            httpGet:
              path: /health/ready
              port: {{ .Values.apikeyman.config.port }}
              httpHeaders:
                - name: Host
                  value: '127.0.0.1'
          {{- toYaml $readinessProbe | nindent 12 }}
          {{- end }}
          startupProbe:
            {{- if .Values.deployment.customStartupProbe }} 
              {{- toYaml .Values.deployment.customStartupProbe | nindent 12 }}
            {{- else }}
            httpGet:
              path: /health/ready
              port: {{ .Values.apikeyman.config.port }}
              httpHeaders:
                - name: Host
                  value: '127.0.0.1'
            {{- toYaml .Values.deployment.startupProbe | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml $resources | nindent 12 }}
          env:
            {{- if not (empty ( include "apikeyman.dsn" . )) }}
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "apikeyman.secretname" . }}
                  key: dsn
            {{- end }}
            - name: GIN_MODE
              value: release
            {{- with .Values.deployment.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: {{ include "apikeyman.name" . }}-config-volume
              mountPath: /etc/config
              readOnly: true
          {{- with $extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if $extraContainers }}
          {{- tpl $extraContainers . | nindent 8 }}
        {{- end }}
      volumes:
        - name: {{ include "apikeyman.name" . }}-config-volume
          configMap:
            name: {{ include "apikeyman.fullname" . }}-config
      {{- with $extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with $nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
