{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apikeyman.secretname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "apikeyman.labels" . | indent 4 }}
  annotations:
{{- with .Values.secret.secretAnnotations }}
  {{- toYaml . | nindent 4 }}
{{- end }}
type: Opaque
data:
  dsn: {{ include "apikeyman.dsn" . | b64enc | quote }}
{{- end }}
