{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apikeyman.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/component: service
    {{- include "apikeyman.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.service.type "ClusterIP" }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.apikeyman.config.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
      appProtocol: {{ .Values.service.appProtocol }}
  selector:
    app.kubernetes.io/name: {{ include "apikeyman.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}