apiVersion: v2
name: apikeyman
description: API Keys manager and authenticator
type: application
keywords:
  - api-security
  - security
sources:
  - https://github.com/jaspeen/apikeyman
version: 0.1.7
appVersion: "0.1.6"
